# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1}]

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_0/zynq_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_bram_ctrl_0_0/zynq_design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zynq_design_1_axi_bram_ctrl_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_blk_mem_gen_0_0/zynq_design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==zynq_design_1_blk_mem_gen_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_axi_periph_0/zynq_design_1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_axi_periph_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_processing_system7_0_100M_0/zynq_design_1_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_processing_system7_0_100M_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_0 || ORIG_REF_NAME==zynq_design_1_xbar_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_0 || ORIG_REF_NAME==zynq_design_1_auto_pc_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_1 || ORIG_REF_NAME==zynq_design_1_auto_pc_1}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_0/zynq_design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design_1/ip/zynq_design_1_axi_bram_ctrl_0_0/zynq_design_1_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_blk_mem_gen_0_0/zynq_design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_rst_processing_system7_0_100M_0/zynq_design_1_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_rst_processing_system7_0_100M_0/zynq_design_1_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq_design_1/ip/zynq_design_1_rst_processing_system7_0_100M_0/zynq_design_1_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0_ooc.xdc

# XDC: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1_ooc.xdc

# XDC: bd/zynq_design_1/zynq_design_1_ooc.xdc
